### ISSUE TITLE
请问文章下面的蓝色条状分享button是怎么配置的呢。

### ISSUE THREAD

**Issue by JackEggie** [SylvanasSun/sylvanassun.github.io#3]
你好，如题。

**Comment by SylvanasSun** [comment]
那个是使用了ShareSDK提供的接口，地址：http://www.mob.com/




------------------ 原始邮件 ------------------
发件人: "Jack Tang";<notifications@github.com>;
发送时间: 2018年1月11日(星期四) 下午4:42
收件人: "SylvanasSun/sylvanassun.github.io"<sylvanassun.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [SylvanasSun/sylvanassun.github.io] 请问文章下面的蓝色条状分享button是怎么配置的呢。 (#3)




你好，如题。

**Comment by JackEggie** [comment]
谢谢，我最后采用的是[need-more-share](https://github.com/revir/need-more-share2)。
